apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-chatbot-2026020501-app-tekton
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/test-chatbot-2026020501/overlays/tekton
    repoURL: https://github.com/fpetk-rolling-demo/test-chatbot-2026020501-gitops.git
    targetRevision: main
  destination:
    namespace: rhdh-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
